# These are supported funding model platforms
[GitHub Sponsors](https://github.com/sponsors) | `github: dabeani`
[Kaufen Sie mir einen Kaffee](https://www.buymeacoffee.com/) | `buy_me_a_coffee: bmks`
